[package]
name = "rust_audio_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.18.1"
gdk-pixbuf = "0.19.8"
glib = "0.19.9"
gstreamer = "0.22.6"
gstreamer-pbutils = "0.22.6"
